### ISSUE TITLE
Error in debug target

### ISSUE THREAD

**Issue by YaroslavLitvinov** [zerovm/zerovm#284]
Zerovm wan't compile in debug mode in Ubuntu 14.04, gcc 4.8.2:
<code>make debug</code>
leads to error:
<code>/usr/bin/ld: lib/gtest/libgtest.a(gtest-all.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
</code>
